# image name: opencv-flask
# VERSION     1

FROM python:3.9.6-buster
LABEL maintainer="bo.yan@csiro.au"

ADD requirements.txt /app/requirements.txt

RUN pip install -r /app/requirements.txt

EXPOSE 5000